added video acquisition code
EmrNITK/GestureControl pull request #13
Opened 2022-10-19 19:15 UTC by m-kritika

2022-10-19 19:36 UTC, hailer24 approved these changes

2022-10-19 19:48 UTC, Sanchit-sk requested changes
Rename the file to something like gesture_control.py. We would be adding more code to this file only.

2022-10-19 19:48 UTC, Sanchit-sk commented on vdo_cptr.py
> +    var = cv2.waitKey(1)
Change to name to a bit more descriptive one instead of var (something like key or keyPressed)

2022-10-20 08:30 UTC, PK-cod3ch3mist approved these changes

2022-10-20 08:31 UTC, PK-cod3ch3mist commented
Merging this to main now.

2022-10-20 08:31 UTC, merged